version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "module"
      POSTGRES_USER: "module"
      POSTGRES_PASSWORD: "module123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"